{% set pd_prefix = pillar.get('instance_prefix', '') -%}
{% set pd_name = pd_prefix + '-influxdb-pd') -%}

kind: PersistentVolume
apiVersion: v1
metadata:
  name: influxdb-pv
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "influxdb-pv"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: {{ pd_name }}
    fsType: ext4
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""